# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - docker-demo-rohit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: dockerdemorohit.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_1BF0A7623AA04BCDB3BB01F709C549F5 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_B748B7C74BF54E9E8899A1F629BCD660 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dockerdemorohit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_1BF0A7623AA04BCDB3BB01F709C549F5 }}/dockerdemo:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0A2DDC4E27744ABBB4C98571E1DE0F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7140DF1AE0C14EF99B3DDC544EDAFD7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9731E956B6A14C34B3ED58FFC6D0BE24 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'docker-demo-rohit'
          slot-name: 'Production'
          images: 'dockerdemorohit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_1BF0A7623AA04BCDB3BB01F709C549F5 }}/dockerdemo:${{ github.sha }}'
          