# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlops-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: mlopsdockerdemo.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11E6BFF641A84480A14A0F06FE327C18 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_83CF99F7A738457EBE59FAC365848285 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mlopsdockerdemo.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11E6BFF641A84480A14A0F06FE327C18 }}/mlops-docker-demo:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86B71F62127C41EFBA24CB37CF73AB83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D5908DAC0E245778D3EAAFCE27BC843 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FDA6DA70863E4DB0A84773208BF8003D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mlops-demo'
          slot-name: 'Production'
          images: 'mlopsdockerdemo.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11E6BFF641A84480A14A0F06FE327C18 }}/mlops-docker-demo:${{ github.sha }}'
          